services:
  app:
    build: .
    container_name: app
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./:/src/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://fastapi:fastapi@db/fastapi

  db:
    image: postgres:12.1-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_PASSWORD=fastapi
      - POSTGRES_DB=fastapi

volumes:
  postgres_data:
